### ISSUE TITLE
LDAP users are not registered on creation

### ISSUE THREAD

**Issue by alecghica** [collective/collective.xmpp.core#11]
@jcbrand reported that LDAP users aren't registered automatically when they are created. Looks like the subscriber under _collective.xmpp.core/subscribers/user_management.py_ is not catching this event.

**Comment by jcbrand** [comment]
Hi @alecghica, can you explain to me how this issue was fixed?

The auto-register feature is not enough. Ideally, it should be possible to have that feature turned off, and still have LDAP users registered on the XMPP server as soon as they are created.

Is that currently possible?

**Comment by alecghica** [comment]
@jcbrand what do you mean? This issue is not fixed, is still an open issue. Maybe you got confused about this issue being referenced by me from a closed issue?

**Comment by jcbrand** [comment]
Ah yes, that was it, thanks!

Ok, I'll investigate this one soon.

**Comment by jcbrand** [comment]
I've taken a look at this and don't see a way to register LDAP users on creation, since they don't ever seem to be "created" in the normal sense.

I think it's enough for now to have user registered for XMPP upon login, that solves the problem for LDAP users.

I'm in any case considering dropping the XMPP registration upon user creation, because of VCards. When the user creation PAS event is fired, the user's properties are not set, so we can in any case not properly set a VCard.

**Comment by alecghica** [comment]
@jcbrand I think registering users upon login make registration of users upon creation redundant as they will be anyway be registered on login. If you ask me the registration of users on creation can be removed.

**Comment by jcbrand** [comment]
On Wed, 2013-02-27 at 02:00 -0800, Alexandru Ghica wrote:

> @jcbrand I think registering users upon login make registration of
> users upon creation redundant as they will be anyway be registered on
> login. If you ask me the registration of users on creation can be
> removed.

Yes, I tend to agree. 

If we enable registration on login, it means that you can only add a
user as a chat buddy once they have logged in. 

The nice thing of immediate registration (upon creation) was that users
could immediately add a user created by an admin as a chat buddy
(without having to wait for that user to log in).

I don't know however how important this is, and it's becoming a pain to
support.

**Comment by alecghica** [comment]
@jcbrand indeed the usecase you described make sense. I think right now most if not all the scenarios for registering users for XMPP are covered. Maybe we can add an info that LDAP users are not registered on creation and has to be added manually and this will solve the issue.

**Comment by jcbrand** [comment]
On Wed, 2013-02-27 at 03:20 -0800, Alexandru Ghica wrote:

> @jcbrand indeed the usecase you described make sense. I think right
> now most if not all the scenarios for registering users for XMPP are
> covered. Maybe we can add an info that LDAP users are not registered
> on creation and has to be added manually and this will solve the
> issue.

Unfortunately not, because VCards complicate things :)

For VCards to work, we need the user's memberdata properties to be up to
date.

XMPP Registration and VCard creation happen together.

The PlonePAS event that signals user creation, is called BEFORE a user's
memberdata properties are set (very stupid IMHO), so at that time it's
useless to set a user's VCard.

If the user is registered for XMPP upon login, their memberdata
properties will already be set.

So I think it actually makes sense to remove XMPP registration upon
creation and only have it manually via the configlet or via login.

On more thing we then need for proper VCard support, is to know when an
existing user has changed their memberdata properties. Currently there's
no event for that AFAIK, so no simple way to hook in to.

**Comment by alecghica** [comment]
I see ... I almost got a headache reading this :)

**Comment by jean** [comment]
On Wed, Feb 27, 2013 at 7:26 PM, JC Brand notifications@github.com wrote:

> The PlonePAS event that signals user creation, is called BEFORE a user's
> memberdata properties are set

Is this baked in?  Or would a pull request to PAS be a similar amount of work
as working around this event order issue?

## 

jean                                              . .. .... //\\oo///\

**Comment by jcbrand** [comment]
On Wed, 2013-02-27 at 04:44 -0800, Jean Jordaan wrote:

> On Wed, Feb 27, 2013 at 7:26 PM, JC Brand notifications@github.com
> wrote:
> 
> > The PlonePAS event that signals user creation, is called BEFORE a
> > user's
> > memberdata properties are set
> 
> Is this baked in? Or would a pull request to PAS be a similar amount
> of work as working around this event order issue?

Yeah, good question. I've considered "fixing" this, but I'm not sure
what's the best approach.

We listen to IPrincipalCreated to know when a user was created.

IPrincipalCreated is called in _doAddUser in
Products.PluggableAuthService.py:962.

In Products.CMFCore.MembershipTool.py:473 _doAddUser is called, and then
afterwards the memberdata props are set.

We actually need to know not only when a user was created, but every
time they update their memberdata props, because we then want to update
their XMPP VCard.

So it's actually something a bit different than IPrincipalCreated, and I
haven't found anything currently existing.

Once place that appears to be good for this, is notifyModifed in
Products.CMFCore/MemberDataTool.py:250 (which actually doesn't fire any
events). Problem is, when a user manually changes memberdata props via
personal prefs page, the memberdata props are set one by one, so
notifyModified is called for every single memberdata property, and not
only once.

This is crap from the perspective of setting the user's XMPP VCard,
because you want to do it once, not spam the XMPP server x times every
time the user updates their profile data.

Concerning our "workaround"...

The question of when to update the user's VCard won't go away if we
disable XMPP registration upon member object creation (and instead only
do it manually or upon login), because we need to update the VCard any
time they change their memberdata props.

So this still requires some thinking :)

**Comment by jcbrand** [comment]
@alecghica I'm sure you'll have a proper headache after reading my last message :)

**Comment by alecghica** [comment]
@jcbrand hehe nah, just kidding, your comment is crystal clear ;)
